server:
  port: 8081

spring:
  h2:
    console:
      enabled:
        true
  datasource:
    url:
      jdbc:h2:mem:testdb
    driverClassName:
      org.h2.Driver
    username:
      sa
  jpa:
    database-platform:
      org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
#    show-sql: true

roles:
  map:
    abcd: 1
    bcbd: 2
    cdbd: 3
  nowemapy:
    1: admin
    2: bussines
    3: normal
#input:
##  name: raja
##  age: 12
#  somedata:
#    abcd: 1
#    bcbd: 2
#    cdbd: 3
